name: Build and Deploy
on:
  push:
    branches:
      - beta

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@beyounglabs'
      - run: yarn install
      - run: npm run npm:publish-beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
