name: Build and Deploy
on:
  push:
    branches:
      - master
      - v2

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: npm run npm:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
